apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: demoservice
  labels:
    app: demoservice
spec:
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: demoservice
        tier: compute
    spec:
      containers:
       - name: demoservice

         image: gcr.io/wise-philosophy-221104/jib-demo
         ports:
         - containerPort: 80

      imagePullSecrets:
       - name: cs1secret
