apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    run: gcpdemoservice
  name: gcpdemoservice
spec:
  type: NodePort
  ports:
  - port: 80
    protocol: TCP
    targetPort: 8081
    nodePort: 32222
  selector:
    run: gcpdemoservice
status:
  loadBalancer: {}
